# This file was generated by GoReleaser. DO NOT EDIT.
class Hookah < Formula
  desc "Simple git hooks manager"
  homepage "https://github.com/Arkweid/hookah"
  url "https://github.com/Arkweid/hookah/releases/download/v0.2.0/hookah_0.2.0_darwin_amd64.tar.gz"
  version "0.2.0"
  sha256 "2b1ee1268a10e8e21beef2c4fed18fbd50ffe289cda55147a2e889e128cb8d28"

  def install
    bin.install "hookah"
  end

  test do
    system "#{bin}/hookah -v"
  end
end
