# This file was generated by GoReleaser. DO NOT EDIT.
class Hookah < Formula
  desc "Simple git hooks manager"
  homepage "https://github.com/Arkweid/hookah"
  url "https://github.com/Arkweid/hookah/releases/download/v0.2.1/hookah_0.2.1_MacOS_x86_64.tar.gz"
  version "0.2.1"
  sha256 "cfb2a3d2b6fb83707b94fc7bfca2603b18f2d89f4fdc18e6c2fac1be163aacdb"

  def install
    bin.install "hookah"
  end

  test do
    system "#{bin}/hookah -v"
  end
end
