# This file was generated by GoReleaser. DO NOT EDIT.
class Lefthook < Formula
  desc "Lefthook a single dependency-free binary to manage all your git hooks that works with any language in any environment, and in all common team workflows"
  homepage "https://github.com/Arkweid/lefthook"
  url "https://github.com/Arkweid/lefthook/releases/download/v0.5.7/lefthook_0.5.7_MacOS_x86_64.gz"
  version "0.5.7"
  sha256 "ae6cf0b78501ce5bd2eda0724f967a983f5fd03ba4ef7c3bc03fb77018c218ac"

  def install
    bin.install "lefthook"
  end

  test do
    system "#{bin}/lefthook version"
  end
end
